services:
  - type: web
    name: hospital-management
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn h_m.wsgi:application
    workingDir: h_m
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: h_m.settings
