services:
  - type: web
    name: Hospital_Resource_Management_System
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn h_m.h_m.wsgi:application
    envVars:
      - key: PYTHON_VERSION
<<<<<<< HEAD
        value: 	3.11.9

=======
        value: 	3.13.4
      - key: DJANGO_SETTINGS_MODULE
        value: h_m.settings
>>>>>>> 8a8834a (Fix: Set full PYTHON_VERSION in render.yaml)
