services:
  - type: web
    name: hospital-resource-management
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn h_m.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: h_m.settings
      - key: PYTHON_VERSION
        value: 3.11.9
